# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Resume Felisha Philander
email: felish.philander@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog

url: "felisha-philander.surge.sh" # the base hostname & protocol for your site, e.g. http://example.com
# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.


#Profile information
name: Felisha Philander-Zils
tagline: Qlikview Developer
pic:   #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below


#sidebar links
email: felisha.philander@gmail.com
phone: 083 262 8593
website: felisha-philander.surge.sh #do not add http://
linkedin: felisha-philander

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
